[issue 35] add check for googlecode_upload (to guard against missing downloads)

diff --git a/jsonschema2pojo-core/src/main/scripts/jsonschema2pojo-upload-release b/jsonschema2pojo-core/src/main/scripts/jsonschema2pojo-upload-release
--- a/jsonschema2pojo-core/src/main/scripts/jsonschema2pojo-upload-release
+++ b/jsonschema2pojo-core/src/main/scripts/jsonschema2pojo-upload-release
@@ -10,6 +10,11 @@ if [[ ! ("$#" == 3 ) ]]; then
     exit 1
 fi
 
+if [[ "`which googlecode_upload`" == "" ]]; then
+    echo "Missing required command 'googlecode_upload'"
+    exit 1
+fi
+
 OLD_VERSION=$1
 VERSION=$2
 WORKING_DIR=/tmp/jsonschema2pojo
